[package]
name = "sequencer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "^1.4.0"
cpal = "0.14.*"
rusty_link = "^0.3.3"

